version: '3.8'

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - "8123:8123"

  # Optional: You can also run the Selenium tests in a containerized environment
  # selenium-chrome:
  #   image: selenium/standalone-chrome
  #   ports:
  #     - "4444:4444"
